# Data Append Exercise:
The datacollected is given in two files namely Preprocessing_Data_I and Preprocessing_Data_II. Can you append the second file with the first one?

In [1]:
#import the package
import pandas as mypd

In [2]:
#import the data1
mydata1=mypd.read_excel(r'D:\Python_ISI\data\Preprocessing_Data_I.xlsx')

In [3]:
mydata1

,SL No,Reviewer_Skill,Review_Type,Domain_Knowledge,Review_Time,Test_Coverage,Review_Coverage,Reuse,Review_Rate,Sprint_Prod
0,1,4,1,4,30.0,100.0,70.0,30,3,0.46
1,2,5,2,5,20.0,70.0,100.0,15,1,0.08
2,3,4,1,4,20.0,70.0,100.0,15,2,0.11
3,4,4,1,4,30.0,70.0,70.0,50,4,0.73
4,5,5,2,5,NaN,100.0,NaN,50,4,0.50
5,6,3,1,3,30.0,100.0,70.0,25,1,0.35
6,7,4,2,4,30.0,70.0,100.0,25,2,0.19
7,8,4,1,4,20.0,70.0,70.0,10,4,0.23
8,9,3,1,3,30.0,70.0,70.0,20,3,0.16
9,10,5,2,5,20.0,70.0,100.0,70,4,1.60
10,11,3,1,3,30.0,100.0,70.0,30,1,0.37
11,12,4,1,4,30.0,100.0,70.0,50,2,0.76
12,13,4,1,4,30.0,100.0,100.0,50,2,0.66
13,14,5,2,5,20.0,70.0,100.0,70,4,1.27
14,15,4,2,4,30.0,50.0,50.0,50,2,0.57
15,16,4,1,4,30.0,NaN,50.0,50,3,0.52
16,17,4,2,4,30.0,50.0,50.0,50,2,0.50
17,18,5,2,5,20.0,70.0,70.0,70,4,0.99
18,19,5,2,5,20.0,70.0,70.0,70,4,0.92
19,20,3,1,3,20.0,70.0,70.0,15,3,0.26

In [4]:
#import the data2
mydata2=mypd.read_csv(r'D:\Python_ISI\data\Preprocessing_Data_II.csv')

In [5]:
mydata2

,SL No,Reviewer_Skill,Review_Type,Domain_Knowledge,Review_Time,Test_Coverage,Review_Coverage,Reuse,Review_Rate,Sprint_Prod
0,21,5,2,5,20.0,50,50.0,50.0,3,0.54
1,22,3,1,3,20.0,100,70.0,10.0,2,0.18
2,23,4,1,4,20.0,100,NaN,10.0,3,0.37
3,24,4,1,4,20.0,100,70.0,20.0,3,0.47
4,25,3,1,3,NaN,100,70.0,25.0,1,0.37
5,26,4,2,4,30.0,70,50.0,70.0,2,0.78
6,27,3,1,3,20.0,100,70.0,20.0,1,0.34
7,28,3,1,3,20.0,100,70.0,20.0,1,0.38
8,29,4,2,4,30.0,100,70.0,NaN,2,0.52
9,30,5,2,5,20.0,100,70.0,70.0,4,1.26
10,31,4,2,4,30.0,100,70.0,10.0,1,0.32
11,32,4,2,4,30.0,70,100.0,10.0,1,0.09
12,33,5,2,5,20.0,70,70.0,70.0,4,1.69
13,34,5,2,5,30.0,50,50.0,50.0,2,0.73

In [8]:
#Append the files
mydata=mydata1.append(mydata2,ignore_index=True)

C:\Users\Anannya\AppData\Local\Temp\ipykernel_11120\426689538.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  mydata=mydata1.append(mydata2,ignore_index=True)

In [9]:
mydata

,SL No,Reviewer_Skill,Review_Type,Domain_Knowledge,Review_Time,Test_Coverage,Review_Coverage,Reuse,Review_Rate,Sprint_Prod
0,1,4,1,4,30.0,100.0,70.0,30.0,3,0.46
1,2,5,2,5,20.0,70.0,100.0,15.0,1,0.08
2,3,4,1,4,20.0,70.0,100.0,15.0,2,0.11
3,4,4,1,4,30.0,70.0,70.0,50.0,4,0.73
4,5,5,2,5,NaN,100.0,NaN,50.0,4,0.50
5,6,3,1,3,30.0,100.0,70.0,25.0,1,0.35
6,7,4,2,4,30.0,70.0,100.0,25.0,2,0.19
7,8,4,1,4,20.0,70.0,70.0,10.0,4,0.23
8,9,3,1,3,30.0,70.0,70.0,20.0,3,0.16
9,10,5,2,5,20.0,70.0,100.0,70.0,4,1.60
10,11,3,1,3,30.0,100.0,70.0,30.0,1,0.37
11,12,4,1,4,30.0,100.0,70.0,50.0,2,0.76
12,13,4,1,4,30.0,100.0,100.0,50.0,2,0.66
13,14,5,2,5,20.0,70.0,100.0,70.0,4,1.27
14,15,4,2,4,30.0,50.0,50.0,50.0,2,0.57
15,16,4,1,4,30.0,NaN,50.0,50.0,3,0.52
16,17,4,2,4,30.0,50.0,50.0,50.0,2,0.50
17,18,5,2,5,20.0,70.0,70.0,70.0,4,0.99
18,19,5,2,5,20.0,70.0,70.0,70.0,4,0.92
19,20,3,1,3,20.0,70.0,70.0,15.0,3,0.26
20,21,5,2,5,20.0,50.0,50.0,50.0,3,0.54
21,22,3,1,3,20.0,100.0,70.0,10.0,2,0.18
22,23,4,1,4,20.0,100.0,NaN,10.0,3,0.37
23,24,4,1,4,20.0,100.0,70.0,20.0,3,0.47
24,25,3,1,3,NaN,100.0,70.0,25.0,1,0.37
25,26,4,2,4,30.0,70.0,50.0,70.0,2,0.78
26,27,3,1,3,20.0,100.0,70.0,20.0,1,0.34
27,28,3,1,3,20.0,100.0,70.0,20.0,1,0.38
28,29,4,2,4,30.0,100.0,70.0,NaN,2,0.52
29,30,5,2,5,20.0,100.0,70.0,70.0,4,1.26
30,31,4,2,4,30.0,100.0,70.0,10.0,1,0.32
31,32,4,2,4,30.0,70.0,100.0,10.0,1,0.09
32,33,5,2,5,20.0,70.0,70.0,70.0,4,1.69
33,34,5,2,5,30.0,50.0,50.0,50.0,2,0.73

In [10]:
mydata.to_excel(r'D:\Python_ISI\Modified_data.xlsx',index=False)